#!/usr/bin/env bash

METRICS="Search time\|Initial heuristic\|Plan length\|f ="

for file in ./castle/castle*.pddl; do
    echo "File: $file"
    echo "Optimal implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "astar(lmcut())" | grep "$METRICS"
    )
    echo "Optimal-relaxed implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "astar(lmcut())" --translate-options --relaxed | grep "$METRICS"
    )
    echo "FF implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "eager_greedy([ff()])" | grep "$METRICS"
    )
    echo "PlanOpt-FF implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "eager_greedy([planopt_ff()])" | grep "$METRICS"
    )
    echo
done
