#!/usr/bin/env bash

METRICS="Initial heuristic value\|Search time\|Plan length\|Expanded [[:digit:]]"

for file in ./castle/castle*.pddl; do
    echo "File: $file"
    echo "Blind implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "astar(blind())" | grep "$METRICS"
    )
    echo "PlanOpt RTG implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "astar(planopt_relaxed_task_graph())" | grep "$METRICS"
    )
    echo
done
