#!/usr/bin/env bash

for file in ./castle/castle*.pddl; do
    echo "File: $file"
    echo "Optimal implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "astar(lmcut())" --translate-options --relaxed | grep "Search time\|Initial heuristic\|Plan length"
    )
    echo "Blind implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "eager_greedy([ff()])" | grep "Search time\|Initial heuristic\|Plan length"
    )
    echo "PlanOpt implementation"
    (
        ulimit -t 60
        ulimit -v 2000000
        ./fast-downward/fast-downward.py $file --search "eager_greedy([planopt_ff()])" | grep "Search time\|Initial heuristic\|Plan length"
    )
done
